### ISSUE TITLE
右下角加入实时网速显示等小工具

### ISSUE THREAD

**Issue by omaidb** [ghostplant/ubuntu-classic#10]
大佬您好，偶然体验了您的系统，感觉很流畅，以前我用xfce桌面的时候，可以自己安装很多小工具，比如实时显示网速，机器温度，资源占用情况等，我没注意这个是什么桌面，希望在能尽快增加这些实用桌面工具哦

**Comment by ghostplant** [comment]
18.04可以考虑支持

**Comment by ghostplant** [comment]
18.04测试版在目前ppa链接中的b/目录可以下载到：bionic-mate-amd64

**Comment by omaidb** [comment]
大佬，您的插件鼓捣的怎么样了

**Comment by ghostplant** [comment]
系统监视器有实时网速不够吗？

**Comment by omaidb** [comment]
不够啊，我希望右下角能时刻查看当前网速

**Comment by ghostplant** [comment]
还需要一段时间，先确定官方要不要支持

**Comment by omaidb** [comment]
好的，大佬，您看看能不能把这个插件移植过来
http://omaidb.com/post-5260.html

**Comment by ghostplant** [comment]
更新已经可以支持实时网速指示器（缺省不启动），需要更新到最新源；

方法一，安装最新镜像，下载地址：
http://ppa.launchpad.net/ghostplant/cdimages/ubuntu/pool/main/b

方法二，旧系统滚动升级：
```sh
sudo apt update
sudo apt dist-upgrade
```

在更新完成之后，打开 "开始菜单"->"首选项"->"启动应用程序"，找到 “网络负载指示器” 并勾选自启动，保存后注销，重新登录会话即可有时是网速小工具。

**Comment by omaidb** [comment]
启用了
