### ISSUE TITLE
telegram无法输入中文

### ISSUE THREAD

**Issue by omaidb** [ghostplant/ubuntu-classic#12]
今天安装完telegram 发现死活输入不了中文。
以前用arch的时候，也遇到过同类问题，最后都自己搞好了，但是您这个定制版没有资料参考，不知道怎么搞，希望您能给出答案

**Comment by ghostplant** [comment]
@omaidb 你是从哪里安装的telegram啊？

**Comment by ghostplant** [comment]
@omaidb Ubuntu 18.04 上是这样解决的：sudo apt install fcitx-frontend-qt5 qt5-styles-plugins
然后需要重启一下系统或者会话：sudo service lightdm restart

**Comment by omaidb** [comment]
@ghostplant 可是，这个版本是基于16.04的呀

**Comment by omaidb** [comment]
sudo apt install fcitx-frontend-qt5 qt5-styles-plugins
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 qt5-styles-plugins

**Comment by ghostplant** [comment]
安装完第一个包然后重启

**Comment by omaidb** [comment]
手动安装完qt5-style-plugins_5.0.0-1build3_amd64.deb  重启后但是没有效果

**Comment by omaidb** [comment]
对了，有截图工具么？

**Comment by ghostplant** [comment]
不用安装qt5-style，那个是18.04才有的包。16.04只需要安装frontend-qt5

**Comment by ghostplant** [comment]
print screen无效吗

**Comment by omaidb** [comment]
已安装fcitx-frontend-qt5 卸载qt5-style-plugins，重启无效

**Comment by ghostplant** [comment]
18.04在这里下载，以后只维护这个新版了：
http://ppa.launchpad.net/ghostplant/flashback/ubuntu/pool/main/b/bionic-mate-desktop-amd64/

apt安装上面两个包，然后重启在18.04测试通过。16.04未测

**Comment by omaidb** [comment]
这可如何是好，那怎么在线升级到你的18.04

**Comment by omaidb** [comment]
不想折腾U盘了

**Comment by ghostplant** [comment]
你在grub控制台可以硬盘模式安装，不过需要你了解grub命令~

**Comment by ghostplant** [comment]
16.04在18.04发布之后会慢慢淘汰，总会要更新的，18.04采用4.15的最新内核，而16.04仅为4.4，已经是两年前的系统了

**Comment by omaidb** [comment]
我现在实施18.04

**Comment by omaidb** [comment]
我用UNetbootin写进U盘试一下，希望能安装成功

**Comment by ghostplant** [comment]
linux下直接用dd命令就好了啊

**Comment by omaidb** [comment]
DD命令用的不熟……

**Comment by ghostplant** [comment]
sudo dd if=ubuntu.iso of=/dev/sdX bs=1M && sync

**Comment by omaidb** [comment]
对了，测试版的18.04版本到时候能升级到正式版吗

**Comment by ghostplant** [comment]
可以，滚动升级，不用重新安装

**Comment by ghostplant** [comment]
原地 apt update && apt dist-upgrade 即可

**Comment by omaidb** [comment]
那就好

**Comment by ghostplant** [comment]
sdX 换成 正确的usb盘号应该知道吧，比如sdc，别写错盘号，否则可能抹掉硬盘

**Comment by omaidb** [comment]
知道呢

**Comment by omaidb** [comment]
DD命令没有进度，不够直观

**Comment by omaidb** [comment]
18.04装好了，Wi-Fi启动不了

**Comment by omaidb** [comment]
内核的原因，16.04升级内核也有这个毛病

**Comment by omaidb** [comment]
现在咋整呢

**Comment by ghostplant** [comment]
那就是说18.04的驱动不支持你的网卡？

**Comment by ghostplant** [comment]
一个方案可以是加入16.04 xenial源安装旧版本的内核。。

**Comment by ghostplant** [comment]
不过这样的话，即便你用官方原版ubuntu18.04发布也一样支持不了你的网卡型号。。

**Comment by omaidb** [comment]
新内核不应该支持更多的网卡驱动吗，卧槽
ghostplant <notifications@github.com>于2018年3月7日 周三01:20写道：

**Comment by ghostplant** [comment]
太旧的型号也可能放弃支持，比如老ati显卡。等正式版发布前可能官方会进一步更新扩充驱动型号吧

**Comment by omaidb** [comment]
好吧

**Comment by ghostplant** [comment]
Ubuntu 18.04 在 apt 中直接可以安装 telegram-desktop，通过额外安装 fcitx-frontend-qt5 重启可以解决输入法支持：
```sh
sudo apt install telegram-desktop fcitx-frontend-qt5
```

Ubuntu 16.04 输入法的解决方案：刚刚更新了升级包，需要三条命令：
```sh
(telegram 需要自己额外安装)
sudo apt update
sudo apt dist-upgrade
sudo apt install fcitx-frontend-qt5
```
然后重启即可。

**Comment by omaidb** [comment]
18.04 输入中文已经解决

**Comment by ghostplant** [comment]
旧版本滚动升级需要`sudo apt install fcitx-frontend-qt5`

新版本CDIMAGE已经预装此包，直接支持QT5应用的中文输入：
ppa.launchpad.net/ghostplant/cdimages/ubuntu/pool/main/b
