### ISSUE TITLE
有默认的截图工具么？

### ISSUE THREAD

**Issue by omaidb** [ghostplant/ubuntu-classic#13]
对了，刚想截图来着，发现没有截图工具，有推荐的么

**Comment by ghostplant** [comment]
print screen键

**Comment by omaidb** [comment]
笔记本没这个按钮，希望能有个截图工具

**Comment by omaidb** [comment]
以前xfce用的截图工具，可以配置快捷键，直接快捷键截图，非常方便

**Comment by ghostplant** [comment]
有的吧，可能你没看见。也可以用命令，16.04命令为gnome-screenshot，18.04终端命令为scrot

**Comment by ghostplant** [comment]
这版本截图快捷键就是print-screen键。18.04系统设置可以改快捷键，16.04必须要手动修改dconf。

**Comment by omaidb** [comment]
好的

**Comment by omaidb** [comment]
暗示print-screen默认是截取桌面，不是区域截图，没有完全满足需求

**Comment by ghostplant** [comment]
alt+print screen

**Comment by ghostplant** [comment]
默认截图命令 scrot，关闭此issue
