### ISSUE TITLE
18.04 dekstop collapse

### ISSUE THREAD

**Issue by omaidb** [ghostplant/ubuntu-classic#17]
da lao , gang cai zhi xing apt autoremove zhi hou , zi dong xie zai le yi da dui bao, xian zai mei you zhuo mian le. hai keyi shang wang , zen me ba zhuo mian an zhuang hui lai . zai xian deng

**Comment by omaidb** [comment]
大佬，桌面崩溃了，刚才执行autoremove ,自动卸载了数百个包，用DD写了20180310版本提示grub错误无法重装，现在终端已上网，怎么把桌面装回去

**Comment by ghostplant** [comment]
20180310的Live CD安装以后本地系统启动提示grub错误？还是grub错误无法启动Live CD？

**Comment by ghostplant** [comment]
自动卸载了数百个包肯定把核心组件一起卸载了，这个400M最小版本的CD几乎任何一个包都无法继续卸载了，已经最小。

**Comment by ghostplant** [comment]
sudo apt update
sudo apt install gnome-flashback-classic debian-properties-common

**Comment by omaidb** [comment]
刚没等到你上线，我直接装mate了，现在桌面系统已经恢复了

**Comment by omaidb** [comment]
live cd 写进U盘提示gurb错误

**Comment by ghostplant** [comment]
没看明白，是dd刻录出错，无法启动live cd吗？还是可以启动live cd，但无法安装系统到本地磁盘？

**Comment by omaidb** [comment]
无法启动live cd，DD了两次依然不能启动

**Comment by ghostplant** [comment]
1）dd 刻录的时候 sync 了吗？否则可能刻录不完整；
2）不能启动，提示的 log 是什么？

**Comment by ghostplant** [comment]
重新 port 了一版，bionic-mate-desktop-amd64_2018.03.10-ubuntu1.tar.gz
试试看是否可以？注意 dd 以后可能刻录未完成，需要等待 sync 命令完成确保缓存清空。

**Comment by ghostplant** [comment]
@omaidb 发现问题了，UEFI启动liveCD正常，但MBR无法启动liveCD

**Comment by omaidb** [comment]
额！！！大佬，能加个telefram 么。

**Comment by ghostplant** [comment]
telegram比较大，要从源里面安装：sudo apt install telegram-desktop

**Comment by omaidb** [comment]
我是说能私聊么

**Comment by ghostplant** [comment]
没用过这个软件，不清楚里面的功能。。

**Comment by omaidb** [comment]
加个好友

**Comment by omaidb** [comment]
哦。加威信还是qq？

**Comment by omaidb** [comment]
我就是装Crossover 的时候把桌面搞崩溃的。现在想是跑虚拟机呢还是继续折腾Crossover

**Comment by ghostplant** [comment]
你能把提示大量软件删除前后文发log出来吗？我看看是哪里的问题

**Comment by ghostplant** [comment]
linux跑windows直接用虚拟机最好了，推荐virtualbox-qt

**Comment by ghostplant** [comment]
Crossover 兼容性不好，很多windows软件还是不支持的

**Comment by omaidb** [comment]
我history没有设置记录

**Comment by ghostplant** [comment]
用系统自带的qemu也可以
```sh
sudo apt install qemu-kvm python3-pyftpdlib
qemu-boot # 下载Win2003镜像
```

**Comment by omaidb** [comment]
qemu-boot：未找到命令

**Comment by ghostplant** [comment]
因为你把gnome-flashback-classic给卸载了，恢复：

```sh
sudo apt install gnome-flashback-classic debian-properties-common
```

**Comment by omaidb** [comment]
哦
ghostplant <notifications@github.com>于2018年3月11日 周日00:02写道：

**Comment by ghostplant** [comment]
问题已经解决，关闭此issue
