### ISSUE TITLE
更换了源之后提示没有 Release 文件。

### ISSUE THREAD

**Issue by omaidb** [ghostplant/ubuntu-classic#20]
[sudo] admin 的密码： 
忽略:1 http://archive.ubuntu.com/ubuntu boinc InRelease                        
忽略:2 http://archive.ubuntu.com/ubuntu boinc-security InRelease               
命中:3 https://launchpad.proxy.ustclug.org/ghostplant/flashback/ubuntu bionic InRelease
忽略:4 http://archive.ubuntu.com/ubuntu boinc-updates InRelease
忽略:5 http://archive.ubuntu.com/ubuntu boinc-backports InRelease
错误:6 http://archive.ubuntu.com/ubuntu boinc Release
  404  Not Found [IP: 91.189.88.149 80]
错误:7 http://archive.ubuntu.com/ubuntu boinc-security Release
  404  Not Found [IP: 91.189.88.149 80]
错误:8 http://archive.ubuntu.com/ubuntu boinc-updates Release
  404  Not Found [IP: 91.189.88.149 80]
错误:9 http://archive.ubuntu.com/ubuntu boinc-backports Release
  404  Not Found [IP: 91.189.88.149 80]
正在读取软件包列表... 完成
E: 仓库 “http://archive.ubuntu.com/ubuntu boinc Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu boinc-security Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu boinc-updates Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu boinc-backports Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

deb http://archive.ubuntu.com/ubuntu/ boinc main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ boinc-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ boinc-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ boinc-backports main restricted universe multiverse
deb https://launchpad.proxy.ustclug.org/ghostplant/flashback/ubuntu bionic main
# 源碼
#deb-src http://archive.ubuntu.com/ubuntu/ boinc main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu/ boinc-security main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu/ boinc-updates main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu/ boinc-backports main restricted universe multivers

# deb-src https://launchpad.proxy.ustclug.org/ghostplant/flashback/ubuntu bionic main

**Comment by ghostplant** [comment]
拼错boinc了，应该是bionic

**Comment by omaidb** [comment]
改了还是报同样的错

**Comment by omaidb** [comment]
sudo apt update
[sudo] admin 的密码： 
命中:1 https://launchpad.proxy.ustclug.org/ghostplant/flashback/ubuntu bionic InRelease
忽略:2 http://archive.ubuntu.com/ubuntu bioinc InRelease                       
忽略:3 http://archive.ubuntu.com/ubuntu bioinc-security InRelease
忽略:4 http://archive.ubuntu.com/ubuntu bioinc-updates InRelease
忽略:5 http://archive.ubuntu.com/ubuntu bioinc-backports InRelease
错误:6 http://archive.ubuntu.com/ubuntu bioinc Release
  404  Not Found [IP: 91.189.88.152 80]
错误:7 http://archive.ubuntu.com/ubuntu bioinc-security Release
  404  Not Found [IP: 91.189.88.152 80]
错误:8 http://archive.ubuntu.com/ubuntu bioinc-updates Release
  404  Not Found [IP: 91.189.88.152 80]
错误:9 http://archive.ubuntu.com/ubuntu bioinc-backports Release
  404  Not Found [IP: 91.189.88.152 80]
正在读取软件包列表... 完成
E: 仓库 “http://archive.ubuntu.com/ubuntu bioinc Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu bioinc-security Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu bioinc-updates Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 仓库 “http://archive.ubuntu.com/ubuntu bioinc-backports Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。

**Comment by ghostplant** [comment]
bionic 不是 bioinc

**Comment by ghostplant** [comment]
```sh
命中:1 https://launchpad.proxy.ustclug.org/ghostplant/flashback/ubuntu bionic InRelease
```
这里的没有拼错

**Comment by omaidb** [comment]
还真是我拼错了
