### ISSUE TITLE
笔记本亮度无法调节

### ISSUE THREAD

**Issue by leenchan** [ghostplant/ubuntu-classic#5]
VAIO EB37EC
AMD 5650m

**Comment by ghostplant** [comment]
echo 700 | sudo tee /sys/class/backlight/*/brightness

这个命令尝试过了吗？
700是亮度至大小，可调大调小。
想要亮度持久保存的话，打开 /etc/rc.postpone 这个文件把 rfkill 下一行的注释去掉，改成自己希望的亮度值

**Comment by ghostplant** [comment]
没记错的话，在GNOME桌面下用 Fn + 左右方向键也可以调节大小

**Comment by ghostplant** [comment]
Ubuntu 18.04 可以通过 Fn 扩展键调节亮度：
ppa.launchpad.net/ghostplant/cdimages/ubuntu/pool/main/b

关闭此issue
