### ISSUE TITLE
安装脚本无法识别平板/笔记本上的mmc储存，安装时出错

### ISSUE THREAD

**Issue by zhenruyan** [ghostplant/ubuntu-classic#7]
并且unsqashfs安装后 无法保存系统设置，已检查读写权限全部正常

**Comment by ghostplant** [comment]
也就是没有找到/dev/sda设备是吧？mmc设备的主存储设备是什么？/dev/中的哪个文件？

**Comment by ghostplant** [comment]
你的环境里面，主一存储是这个设备吗：/dev/mccblk0  ？

**Comment by ghostplant** [comment]
@zhenruyan 对，为了更好的支持mmc，我已经更新了脚本，是否可以参与测试？如果安装到mcc没有问题，则下次iso更新将会并入该功能。

**Comment by ghostplant** [comment]
@zhenruyan 测试方法
使用当前iso镜像引导笔记本进入LiveCD桌面，首先不急着用安装器安装系统，在这之前，终端中运行如下两条命令更新一下安装器程序：
sudo apt update
sudo apt install ubilite-installer

更新完成之后，新版本安装器应该可以识别mcc设备。

**Comment by zhenruyan** [comment]
好的，我去试试。多谢解决
