### ISSUE TITLE
无法调整分辨率

### ISSUE THREAD

**Issue by osdu** [ghostplant/ubuntu-classic#8]
无法调整桌面分辨率

**Comment by ghostplant** [comment]
VirtualBox下默认分辨率随窗口大小动态适应的。VMware的话应该要装VMTools。
如果不是上面两种虚拟机，那么只能在Ubuntu安装 apt install lxrandr 软件包，通过 lxrandr 命令人工保存分辨率了。

**Comment by osdu** [comment]
@ghostplant xrandr 软件包体积不大，能否默认集成，并且添加常用分辨率的一键设置工具

**Comment by ghostplant** [comment]
这个软件来源于LXDE，引用功能对所有桌面有效，但保存功能只对LXDE有效，目前先看看能不能解决保存问题，可以的话就可以集成。

**Comment by osdu** [comment]
@ghostplant 建议集成，ubuntu-classic 体积小非常适合作为linux应急救援系统，集成后可以在无网络环境下手动调整分辨率

**Comment by ghostplant** [comment]
软件包已经更新了，通过 sudo apt update && sudo apt upgrade 更新后，lxrandr的保存可以重启生效。
本更新在下次打包 iso 光盘镜像时会自然更新进去～

**Comment by ghostplant** [comment]
Ubuntu 18.04 可以在首选项显示器调整分辨率，下载链接：

http://ppa.launchpad.net/ghostplant/cdimages/ubuntu/pool/main/b
