### ISSUE TITLE
希望加上ia32和x86_64的uefi启动支持  

### ISSUE THREAD

**Issue by zhenruyan** [ghostplant/ubuntu-classic#9]
如题

**Comment by ghostplant** [comment]
x86_64的uefi已经支持了，刻录USB的时候需要用dd命令写进去，UltraISO可能不行。
ia32版本你确定可以兼容uefi启动吗？官方ubuntu的32位版本并没有提供对uefi的支持。

**Comment by zhenruyan** [comment]
晚上用ia32的文件试了一下  可以启动iso境像  ，但是把ia32的bootia32.efi和grub.conf文件复制到 efi分区 ，可以正常启动grub，但是会卡死在启动系统的那一瞬间 ，没报任何错误  ，我现在是用的bootia32.efi配合的64位的arch  完美运行   所以应该ubuntu也是支持的  不知道我哪里姿势不对

**Comment by zhenruyan** [comment]
其实只要在数据分区复制一份efi文件夹就可以直接支持UltraISO  我都是直接解压复制到upan的，uefi不需要分区头标记 只要是fat格式的分区，然后有efi这个文件夹就可以

**Comment by zhenruyan** [comment]
不过大佬你真是厉害！ ubuntu+gnome消耗的内存比arch+xfce占用都少！

**Comment by ghostplant** [comment]
EFI 的安装器已经得到了更新，在 20180303 之后的版本都支持 UEFI 的安装。

**Comment by ghostplant** [comment]
20180303之后的Ubuntu16.04/18.04的CDIMAGE已经更好地支持了UEFI的安装。

Ubuntu 18.04下载地址：
http://ppa.launchpad.net/ghostplant/cdimages/ubuntu/pool/main/b

**Comment by zhenruyan** [comment]
大佬请问您是怎么打包成iso的？  我用deboostrap  可以成功做出可以正常启动的squashfs镜像
